{
 "title": "Proxmox Backups",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Backup Size",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(backup_size_bytes{job=\"proxmox-backups\"})",
     "legendFormat": "Total size"
    }
   ]
  },
  {
   "title": "Backup size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "backup_size_bytes{job=\"proxmox-backups\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(backup_size_bytes{job=\"proxmox-backups\"})",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Total Backup Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(backup_duration_seconds{job=\"proxmox-backups\"})",
     "legendFormat": "Total size"
    }
   ]
  },
  {
   "title": "Backup jobs duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backup_duration_seconds{job=\"proxmox-backups\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}